Repository Nordix/Meridio-Operator, pull requests merged in 2022-08, with the labels that each got.

#72 Update to Golang 1.19
  Makefile
  go.mod
  go.sum
Labels: kind/enhancement, size/S

#112 NSM uplift to 1.5.0
  controllers/attractor/lb-fe.go
  controllers/attractor/nse-vlan.go
Labels: kind/enhancement, size/S

#114 Update capabilities according to NSM v1.5
  config/manager/deployment/ipam.yaml
  config/manager/deployment/lb-fe.yaml
  config/manager/deployment/nsp.yaml
  config/manager/deployment/proxy.yaml
Labels: kind/enhancement, area/security, priority/low

#111 Fix for the ephemeral containers
  controllers/attractor/lb-fe.go
  controllers/attractor/nse-vlan.go
  controllers/common/const.go
  controllers/conduit/proxy.go
  controllers/trench/ipam.go
  controllers/trench/nsp.go
Labels: kind/bug, area/configuration, size/S

#117 Remove hostport from the NSE-VLAN container
  config/manager/deployment/nse-vlan.yaml
  controllers/attractor/nse-vlan.go
Labels: kind/bug, area/configuration, size/S

#118 TLS min version set to 1.2 for the webhook server
  main.go
Labels: kind/bug, area/security, size/S
